telegram_token: "1719445982:AAHAeBjWQ2MCdYXLHODrK6j1OxhXirSzF98"
template_path: "/etc/telegrambot/template.tmpl"
time_zone: "America/Sao_Paulo"
split_token: "|"
time_outdata: "02/01/2006 15:04:05"
split_msg_byte: 10000
