global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'Prometheus Monitoring'

rule_files:
  - 'alert.rules'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
      
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9090'] # adicione o ip onde foi criado o serviço
  
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
         - targets: ['192.168.0.185:9100'] # adicione o ip onde foi criado o serviço

  
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
         - targets: ['192.168.0.185:8081'] # adicione o ip onde foi criado o serviço
